
#include <exception>
#include <QApplication>
#include <QDebug>
#include <QDir>
#include <QFile>
#include <QFileInfoList>
#include <qglobal.h>
#include <QIODevice>
#include <QList>
#include <QMainWindow>
#include <QObject>
#include <QPointer>
#include <QResource>
#include <QSettings>
#include <QSqlDatabase>
#include <QSqlError>
#include <QSqlQuery>
#include <QString>
#include <QStringList>
#include <QTextStream>
#include <QTime>
#include <QVariant>
#include <QxtCsvModel>
#include <string>
