
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt4-sql-sqlite libboost1.48-dev libboost-filesystem1.48-dev libboost-system1.48-dev libboost-test1.48-dev libboost-locale1.48-dev

script: "make run-tests"

